server:
  port: 7979
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: springboot-front
  cloud:
    openfeign:
      client:
        config:
          console.url: http://127.0.0.1:8080
      micrometer:
        enabled: true
      circuitbreaker:
        enabled: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: 'true'

logging:
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p"