version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/volume:/prometheus
    ports:
      - "9100:9090"
    expose:
      - "9100"
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - TZ=Asia/Seoul
    networks:
      - valkyrie
    mem_limit: "512mb"
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana/volume:/var/lib/grafana
    ports:
      - "3000:3000"
    expose:
      - "3000"
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - TZ=Asia/Seoul
    networks:
      - valkyrie
    mem_limit: "512mb"
  loki:
    image: grafana/loki
    container_name: loki
    volumes:
      - ./loki/config:/mnt/config
      - ./loki/volume:/loki
    ports:
      - "3100:3100"
    expose:
      - "3100"
    command:
      - '--config.file=/mnt/config/loki-config.yml'
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - TZ=Asia/Seoul
    networks:
      - valkyrie
    mem_limit: "512mb"

networks:
  valkyrie:
    driver: bridge