server:
  port: 8080

spring:
  application:
    name: springboot-api
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:public;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      data-locations: classpath:h2/data.sql
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false