server:
  port: 8080
  tomcat:
    accesslog:
      enabled: false
      #directory:
      max-days: 15
      request-attributes-enabled: true
      pattern: '%h %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"'

spring:
  application:
    name: springboot-api
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:public;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      data-locations: classpath:h2/data.sql
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false

springdoc:
  show-actuator: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: 'true'

logging:
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p"