global:
  scrape_interval: 2s
  scrape_timeout: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'springboot-monitoring'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8080']